### ISSUE TITLE
please auto install ghost cms with external PostgreSQL and Cloudinary image storage 

### ISSUE THREAD

**Issue by bazarbashe** [sumithemmadi/tor-hidden-service-on-heroku#3]
hi Emmadi Sumith Kumar , 
at the first , thank you for make deploy to heroku button at github branch :)
please auto install ghost cms with external PostgreSQL and Cloudinary image storage as index.php file in web
PostgreSQL is free addon & not need to add credit card verify on heroku
this repo is complete productable , now need to auto install with your process : 
https://github.com/SNathJr/ghost-on-heroku
waiting for your response
finest regards

**Comment by sumithemmadi** [comment]
Hi bazarbashe 
- It's very simple to do but it's take little more time , just wait I will explain you how you can do this.
Just clone my repository and add below  dependencies 
to `dependencies` Object in `package.json`  

```bash
    "attila": "github:zutrinken/attila#1.13.0",
    "bleak": "github:zutrinken/bleak#1.4.0",
    "casper": "github:tryghost/Casper#3.0.4",
    "ghost": "^3.2.0",
    "ghost-storage-adapter-s3": "^2.8.0",
    "ghost-storage-cloudinary": "^2.0.2",
    "ghost-webdav-storage-adapter": "^0.3.5",
    "london": "github:tryghost/london#1.0.0",
    "massively": "github:tryghost/massively#1.0.2",
    "mysql": "^2.17.1",
    "the-shell": "github:mityalebedev/The-Shell#v2.0.0",
    "vapor": "github:sethlilly/Vapor#v1.6.0",
    "pico": "github:tryghost/pico",
    "lyra": "github:tryghost/lyra",
    "liebling": "github:snathjr/liebling"
```
- After adding above dependencies to package.json file add  ``` "postinstall": "bash bin/copy-themes.sh && bash bin/copy-webdav-plugin.sh" ``` to  `Scripts`   Objects and save the file.
- Now open app.json file and add below add-ons  to `add-ons` object
```bash
    {
      "plan": "heroku-postgresql",
      "options": {
        "version": "9.5"
        }
    }
    "jawsdb",
    "mailgun",
    "cloudinary"
```
- Now add your  environments  to `env ` object in app.json to know more https://devcenter.heroku.com/articles/app-json-schema
- As per this repo  [ghost-on-heroku](https://github.com/SNathJr/ghost-on-heroku) the env will be  
```
"env": {
    "APP_PUBLIC_URL": {
      "description": "The HTTPS URL of this app: either your custom domain or default 'herokuapp.com' hostname.",
      "value": "https://YOURAPPNAME.herokuapp.com"
    },
    "S3_ACCESS_KEY_ID": {
      "description": "(Optional) Set your AWS Access Key ID to enable S3 file storage. Defaults to Cloudinary storage",
      "required": false
    },
    "S3_ACCESS_SECRET_KEY": {
      "description": "AWS Access Secret Key, if using S3 file storage.",
      "required": false
    },
    "S3_BUCKET_NAME": {
      "description": "Name of your S3 bucket on AWS, if using S3 file storage.",
      "required": false
    },
    "S3_BUCKET_REGION": {
      "description": "Region of your S3 bucket on AWS, if using S3 file storage.",
      "required": false
    },
    "S3_ASSET_HOST_URL": {
      "description": "Optional custom CDN asset host url, if using S3 file storage.",
      "required": false
    },
    "WEBDAV_SERVER_URL": {
      "description": "URL of your WebDAV server, if using WebDAV file storage",
      "required": false
    },
    "WEBDAV_USERNAME": {
      "description": "Username for your WebDAV server, if using WebDAV file storage",
      "required": false
    },
    "WEBDAV_PASSWORD": {
      "description": "Password for your WebDAV server, if using WebDAV file storage",
      "required": false
    },
    "WEBDAV_PATH_PREFIX": {
      "description": "Optional path prefix for your WebDAV server, if using WebDAV file storage",
      "required": false
    },
    "WEBDAV_STORAGE_PATH_PREFIX": {
      "description": "Optional storage path prefix for  your WebDAV server, if using WebDAV file storage",
      "required": false
    }
  }
```
- Then copy   all files and folders to this repo except `Procfile` ,`app.json` and `package.json` file.
- then validate your `app.json`  file , refer to https://www.npmjs.com/package/app.json

- Now push your repository to GitHub 
- Click on `Deploy to Heroku` button
- Follow the instructions shown on [Heroku  Dashboard](https://dashboard.heroku.com/).
- But this type of installation is not good because Heroku will generate  new .onion link everytime when your app restarts  to use permanent onion domain go to my [Repository](https://github.com/sumithemmadi/Tor-Onion-Service-On-Heroku/#quick-start)  and follow from 7th step in [Quick Start](https://github.com/sumithemmadi/Tor-Onion-Service-On-Heroku/#quick-start)  session

**Comment by bazarbashe** [comment]
Hello Again Emmadi Sumith Kumar ,
1 - I go all your steps but in case to :
Copy all files and folders to this repo except Procfile ,app.json and package.json file.
I also removed package-lock.json from ghost repo because overlap with your repo package-lock.json. is it correct ?
2 - server.js file is exist in both repositories , what to do ?
Please if it's possible make new branch diffrent as master & make changes of this work on it .
Waiting for your repsonse
Finest regards

**Comment by sumithemmadi** [comment]
Yesh sure ,I will create completely another repository .

**Comment by bazarbashe** [comment]
hi Emmadi Sumith Kumar ,
I'm waiting for your changes bro :)
please if its possible do it faster ...
finest regards
